### ISSUE TITLE
minicap LGE - armeabi-v7a - Vector<> have different types - Android 10

### ISSUE THREAD

**Issue by man4567890** [openstf/minitouch#62]
With LGE phones, either 32 or 64 bit versions, running Android 10, I'm getting the Vector problem, using stf from  https://github.com/Orange-OpenSource/stf.git

**sdk: '29', - armeabi-v7a**

```
2020-03-31T06:14:20.611Z INF/device:plugins:group 24812 [LMK300QKJ7ZDJRRSMF] Subscribing to group channel "27wYow6vQ7KHx53MvmzFQw=="
2020-03-31T06:14:21.475Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] Setting frame producer projection to 313x583
2020-03-31T06:14:21.476Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] Requesting frame producer to start
2020-03-31T06:14:21.476Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] Launching screen service
2020-03-31T06:14:21.710Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "PID: 6181"
2020-03-31T06:14:21.711Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: Using projection 720x1520@276x583/0"
2020-03-31T06:14:21.711Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:241) Creating SurfaceComposerClient"
2020-03-31T06:14:21.712Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] Connecting to minicap service
2020-03-31T06:14:21.714Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:244) Performing SurfaceComposerClient init check"
2020-03-31T06:14:21.714Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:255) Creating virtual display"
2020-03-31T06:14:21.714Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:261) Creating buffer queue"
2020-03-31T06:14:21.757Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:264) Setting buffer options"
2020-03-31T06:14:21.757Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:268) Creating CPU consumer"
2020-03-31T06:14:21.757Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:272) Creating frame waiter"
2020-03-31T06:14:21.757Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:276) Publishing virtual display"
2020-03-31T06:14:21.758Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] minicap says: **"Vector<> have different types (this=0xbee29160, rhs=0xbee29210)"**
2020-03-31T06:14:21.968Z WRN/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] Shell keeping minicap running ended unexpectedly
2020-03-31T06:14:23.503Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] Disconnecting from minicap service
2020-03-31T06:14:23.504Z INF/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] Stopping minicap service
2020-03-31T06:14:23.505Z FTL/device:plugins:screen:stream 24812 [LMK300QKJ7ZDJRRSMF] Frame producer had an error FailError: Failure: 'closed'
    at /usr/lib/node_modules/stf/node_modules/adbkit/lib/adb/parser.js:183:29
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2020-03-31T06:14:23.505Z FTL/util:lifecycle 24812 [LMK300QKJ7ZDJRRSMF] Shutting down due to fatal error
2020-03-31T06:14:23.513Z INF/provider 21753 [*] Cleaning up device worker "LMK300QKJ7ZDJRRSMF"
2020-03-31T06:14:23.513Z ERR/provider 21753 [*] Device worker "LMK300QKJ7ZDJRRSMF" died with code 1
2020-03-31T06:14:23.513Z INF/provider 21753 [*] Restarting device worker "LMK300QKJ7ZDJRRSMF"
2020-03-31T06:14:24.297Z INF/device:support:push 25973 [LMK300QKJ7ZDJRRSMF] Sending output to "tcp://127.0.0.1:7116"
2020-03-31T06:14:24.301Z INF/device 25973 [LMK300QKJ7ZDJRRSMF] Preparing device
2020-03-31T06:14:24.682Z INF/device:support:sub 25973 [LMK300QKJ7ZDJRRSMF] Receiving input from "tcp://127.0.0.1:7114"
2020-03-31T06:14:24.683Z INF/device:support:sub 25973 [LMK300QKJ7ZDJRRSMF] Subscribing to permanent channel "*ALL"
2020-03-31T06:14:24.801Z INF/device:support:properties 25973 [LMK300QKJ7ZDJRRSMF] Loading properties
2020-03-31T06:14:25.008Z INF/device:support:sdk 25973 [LMK300QKJ7ZDJRRSMF] Supports SDK 29
2020-03-31T06:14:25.009Z INF/device:support:abi 25973 [LMK300QKJ7ZDJRRSMF] Supports ABIs armeabi-v7a, armeabi
2020-03-31T06:14:25.536Z INF/device:resources:minicap 25973 [LMK300QKJ7ZDJRRSMF] Installing "/usr/lib/node_modules/stf/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/bin/minicap" as "/data/local/tmp/minicap"
2020-03-31T06:14:25.536Z INF/device:resources:minicap 25973 [LMK300QKJ7ZDJRRSMF] Installing "/usr/lib/node_modules/stf/node_modules/minicap-prebuilt-beta/prebuilt/armeabi-v7a/lib/android-29/minicap.so" as "/data/local/tmp/minicap.so"
2020-03-31T06:14:25.910Z INF/device:resources:service 25973 [LMK300QKJ7ZDJRRSMF] Checking whether we need to install STFService
2020-03-31T06:14:26.107Z INF/device:resources:service 25973 [LMK300QKJ7ZDJRRSMF] Running version check
2020-03-31T06:14:26.943Z INF/device:resources:service 25973 [LMK300QKJ7ZDJRRSMF] Installing STFService
2020-03-31T06:14:31.564Z INF/device:resources:service 25973 [LMK300QKJ7ZDJRRSMF] STFService up to date
2020-03-31T06:14:31.566Z INF/device:plugins:service 25973 [LMK300QKJ7ZDJRRSMF] Launching agent
2020-03-31T06:14:32.921Z INF/device:plugins:service 25973 [LMK300QKJ7ZDJRRSMF] Agent says: "Starting minitouch agent"
2020-03-31T06:14:32.922Z INF/device:plugins:service 25973 [LMK300QKJ7ZDJRRSMF] Agent says: "Listening on @stfagent"
2020-03-31T06:14:33.038Z INF/device:plugins:service 25973 [LMK300QKJ7ZDJRRSMF] Launching service
2020-03-31T06:14:33.039Z INF/device:plugins:service 25973 [LMK300QKJ7ZDJRRSMF] using 'start-foreground-service' command for API 29
2020-03-31T06:14:33.043Z INF/device:plugins:service 25973 [LMK300QKJ7ZDJRRSMF] Agent says: "InputClient started"
2020-03-31T06:14:33.391Z INF/device:plugins:display 25973 [LMK300QKJ7ZDJRRSMF] Reading display info
2020-03-31T06:14:33.464Z INF/device:plugins:phone 25973 [LMK300QKJ7ZDJRRSMF] Fetching phone info
2020-03-31T06:14:33.493Z INF/device:plugins:identity 25973 [LMK300QKJ7ZDJRRSMF] Solving identity
2020-03-31T06:14:33.496Z INF/device:plugins:solo 25973 [LMK300QKJ7ZDJRRSMF] Subscribing to permanent channel "fpkN20ei7EgGDf4jvo1X9kGdLdQ="
2020-03-31T06:14:33.498Z INF/device:plugins:screen:stream 25973 [LMK300QKJ7ZDJRRSMF] Starting WebSocket server on port 7552
2020-03-31T06:14:33.933Z INF/device:resources:minitouch 25973 [LMK300QKJ7ZDJRRSMF] Installing "/usr/lib/node_modules/stf/node_modules/minitouch-prebuilt-beta/prebuilt/armeabi-v7a/bin/minitouch" as "/data/local/tmp/minitouch"
2020-03-31T06:14:34.130Z WRN/device:plugins:data 25973 [LMK300QKJ7ZDJRRSMF] Unable to find device data { serial: 'LMK300QKJ7ZDJRRSMF',
  platform: 'Android',
  manufacturer: 'LGE',
  operator: '',
  model: 'LM-K300',
  version: '10',
  abi: 'armeabi-v7a',
  sdk: '29',
  product: 'mdh5lm',
  cpuPlatform: 'mt6765',
  openGLESVersion: '3.2',
  marketName: 'mdh5lm',
  display: 
   { id: 0,
     width: 720,
     height: 1520,
     xdpi: 294.9670104980469,
     ydpi: 311.35400390625,
     fps: 61.2400016784668,
     density: 2,
     rotation: 0,
     secure: true,
     size: 5.458133099625045,
     url: 'ws://10.119.102.86:7552' },
  phone: { network: 'UNKNOWN' } }
2020-03-31T06:14:34.134Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] Touch origin is top left
2020-03-31T06:14:34.134Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] Requesting touch consumer to start
2020-03-31T06:14:34.135Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] Launching touch service
2020-03-31T06:14:34.154Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] Connecting to minitouch service
2020-03-31T06:14:34.212Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] minitouch says: "open: Permission denied"
2020-03-31T06:14:34.212Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
2020-03-31T06:14:34.212Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] minitouch says: "Unable to open device /dev/input/event3 for inspectionopen: Permission denied"
2020-03-31T06:14:34.213Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] minitouch says: "Unable to open device /dev/input/mice for inspectionopen: Permission denied"
2020-03-31T06:14:34.214Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
2020-03-31T06:14:34.214Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] minitouch says: "Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device"
2020-03-31T06:14:34.214Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] minitouch says: "using Android InputManager"
2020-03-31T06:14:34.332Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] Reading minitouch banner
2020-03-31T06:14:34.375Z INF/device:plugins:touch 25973 [LMK300QKJ7ZDJRRSMF] minitouch says: "Connection established"
2020-03-31T06:14:34.381Z INF/device:plugins:vnc 25973 [LMK300QKJ7ZDJRRSMF] Starting VNC server on port 7554
2020-03-31T06:14:34.383Z INF/device:plugins:browser 25973 [LMK300QKJ7ZDJRRSMF] Loading browser list
2020-03-31T06:14:34.414Z INF/device:plugins:browser 25973 [LMK300QKJ7ZDJRRSMF] Updating browser list
2020-03-31T06:14:34.416Z INF/device:plugins:mute 25973 [LMK300QKJ7ZDJRRSMF] Will not mute master volume
2020-03-31T06:14:34.866Z INF/device:resources:minirev 25973 [LMK300QKJ7ZDJRRSMF] Installing "/usr/lib/node_modules/stf/vendor/minirev/armeabi-v7a/minirev" as "/data/local/tmp/minirev"
2020-03-31T06:14:35.059Z INF/device:plugins:forward 25973 [LMK300QKJ7ZDJRRSMF] Launching reverse port forwarding service
2020-03-31T06:14:35.081Z INF/device:plugins:forward 25973 [LMK300QKJ7ZDJRRSMF] Connecting to reverse port forwarding service
2020-03-31T06:14:35.256Z INF/device 25973 [LMK300QKJ7ZDJRRSMF] Fully operational
```

And for
**sdk: '29', - arm64-v8a**

```
2020-03-31T05:45:06.647Z INF/device:plugins:group 18277 [LMG820UMb681bd28] Subscribing to group channel "27wYow6vQ7KHx53MvmzFQw=="

2020-03-31T05:45:07.472Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] Setting frame producer projection to 843x843

2020-03-31T05:45:07.472Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] Requesting frame producer to start

2020-03-31T05:45:07.473Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] Launching screen service
2020-03-31T05:45:07.553Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "PID: 13100"
2020-03-31T05:45:07.553Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: Using projection 1080x2340@389x843/0"
2020-03-31T05:45:07.553Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:241) Creating SurfaceComposerClient"
2020-03-31T05:45:07.553Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:244) Performing SurfaceComposerClient init check"
2020-03-31T05:45:07.554Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:255) Creating virtual display"
2020-03-31T05:45:07.554Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:261) Creating buffer queue"
2020-03-31T05:45:07.554Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:264) Setting buffer options"
2020-03-31T05:45:07.554Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:268) Creating CPU consumer"
2020-03-31T05:45:07.555Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:272) Creating frame waiter"
2020-03-31T05:45:07.555Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: "INFO: (external/MY_minicap/src/minicap_29.cpp:276) Publishing virtual display"
2020-03-31T05:45:07.555Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] minicap says: **"Vector<> have different types (this=0x7fea466ef0, rhs=0x7fea467040)"**
2020-03-31T05:45:07.556Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] Connecting to minicap service
2020-03-31T05:45:07.618Z WRN/device:plugins:screen:stream 18277 [LMG820UMb681bd28] Shell keeping minicap running ended unexpectedly
2020-03-31T05:45:09.356Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] Disconnecting from minicap service
2020-03-31T05:45:09.357Z INF/device:plugins:screen:stream 18277 [LMG820UMb681bd28] Stopping minicap service
2020-03-31T05:45:09.358Z FTL/device:plugins:screen:stream 18277 [LMG820UMb681bd28] Frame producer had an error FailError: Failure: 'closed'
    at /usr/lib/node_modules/stf/node_modules/adbkit/lib/adb/parser.js:183:29
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2020-03-31T05:45:09.359Z FTL/util:lifecycle 18277 [LMG820UMb681bd28] Shutting down due to fatal error
2020-03-31T05:45:09.365Z INF/provider 13685 [*] Cleaning up device worker "LMG820UMb681bd28"
2020-03-31T05:45:09.366Z ERR/provider 13685 [*] Device worker "LMG820UMb681bd28" died with code 1
2020-03-31T05:45:09.366Z INF/provider 13685 [*] Restarting device worker "LMG820UMb681bd28"
2020-03-31T05:45:10.189Z INF/device:support:push 19143 [LMG820UMb681bd28] Sending output to "tcp://127.0.0.1:7116"
2020-03-31T05:45:10.193Z INF/device 19143 [LMG820UMb681bd28] Preparing device
2020-03-31T05:45:10.534Z INF/device:support:sub 19143 [LMG820UMb681bd28] Receiving input from "tcp://127.0.0.1:7114"
2020-03-31T05:45:10.535Z INF/device:support:sub 19143 [LMG820UMb681bd28] Subscribing to permanent channel "*ALL"
2020-03-31T05:45:10.623Z INF/device:support:properties 19143 [LMG820UMb681bd28] Loading properties
2020-03-31T05:45:10.681Z INF/device:support:sdk 19143 [LMG820UMb681bd28] Supports SDK 29
2020-03-31T05:45:10.682Z INF/device:support:abi 19143 [LMG820UMb681bd28] Supports ABIs arm64-v8a, armeabi-v7a, armeabi
2020-03-31T05:45:10.951Z INF/device:resources:minicap 19143 [LMG820UMb681bd28] Installing "/usr/lib/node_modules/stf/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/bin/minicap" as "/data/local/tmp/minicap"
2020-03-31T05:45:10.952Z INF/device:resources:minicap 19143 [LMG820UMb681bd28] Installing "/usr/lib/node_modules/stf/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-29/minicap.so" as "/data/local/tmp/minicap.so"
2020-03-31T05:45:11.268Z INF/device:resources:service 19143 [LMG820UMb681bd28] Checking whether we need to install STFService
2020-03-31T05:45:11.340Z INF/device:resources:service 19143 [LMG820UMb681bd28] Running version check
2020-03-31T05:45:11.632Z INF/device:resources:service 19143 [LMG820UMb681bd28] STFService up to date
2020-03-31T05:45:11.634Z INF/device:plugins:service 19143 [LMG820UMb681bd28] Launching agent
2020-03-31T05:45:12.299Z INF/device:plugins:service 19143 [LMG820UMb681bd28] Agent says: "Starting minitouch agent"
2020-03-31T05:45:12.299Z INF/device:plugins:service 19143 [LMG820UMb681bd28] Agent says: "Listening on @stfagent"
2020-03-31T05:45:12.367Z INF/device:plugins:service 19143 [LMG820UMb681bd28] Launching service
2020-03-31T05:45:12.367Z INF/device:plugins:service 19143 [LMG820UMb681bd28] using 'start-foreground-service' command for API 29
2020-03-31T05:45:12.372Z INF/device:plugins:service 19143 [LMG820UMb681bd28] Agent says: "InputClient started"
2020-03-31T05:45:12.544Z INF/device:plugins:display 19143 [LMG820UMb681bd28] Reading display info
2020-03-31T05:45:12.610Z INF/device:plugins:phone 19143 [LMG820UMb681bd28] Fetching phone info
2020-03-31T05:45:12.636Z INF/device:plugins:identity 19143 [LMG820UMb681bd28] Solving identity
2020-03-31T05:45:12.637Z INF/device:plugins:solo 19143 [LMG820UMb681bd28] Subscribing to permanent channel "SnAEz7FrWHnEcjuAY/KjF3gPBNQ="
2020-03-31T05:45:12.638Z INF/device:plugins:screen:stream 19143 [LMG820UMb681bd28] Starting WebSocket server on port 7488
2020-03-31T05:45:12.865Z INF/device:resources:minitouch 19143 [LMG820UMb681bd28] Installing "/usr/lib/node_modules/stf/node_modules/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch" as "/data/local/tmp/minitouch"
2020-03-31T05:45:13.071Z WRN/device:plugins:data 19143 [LMG820UMb681bd28] Unable to find device data { serial: 'LMG820UMb681bd28',
  platform: 'Android',
  manufacturer: 'LGE',
  operator: '',
  model: 'LM-G820',
  version: '10',
  abi: 'arm64-v8a',
  sdk: '29',
  product: 'alphalm_lao_com',
  cpuPlatform: 'msmnile',
  openGLESVersion: '3.2',
  display: 
   { id: 0,
     width: 1080,
     height: 2340,
     xdpi: 422.03021240234375,
     ydpi: 424.5427551269531,
     fps: 60.000003814697266,
     density: 2.625,
     rotation: 0,
     secure: true,
     size: 6.0769116941916055,
     url: 'ws://10.119.102.86:7488' },
  phone: { network: 'UNKNOWN' } }
2020-03-31T05:45:13.075Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] Touch origin is top left
2020-03-31T05:45:13.076Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] Requesting touch consumer to start
2020-03-31T05:45:13.076Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] Launching touch service
2020-03-31T05:45:13.102Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] Connecting to minitouch service
2020-03-31T05:45:13.160Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "open: Permission denied"
2020-03-31T05:45:13.160Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/event7 for inspectionopen: Permission denied"
2020-03-31T05:45:13.160Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/event6 for inspectionopen: Permission denied"
2020-03-31T05:45:13.161Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/event1 for inspectionopen: Permission denied"
2020-03-31T05:45:13.161Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/event4 for inspectionopen: Permission denied"
2020-03-31T05:45:13.161Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/event3 for inspectionopen: Permission denied"
2020-03-31T05:45:13.162Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/mice for inspectionopen: Permission denied"
2020-03-31T05:45:13.162Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/event2 for inspectionopen: Permission denied"
2020-03-31T05:45:13.162Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/event0 for inspectionopen: Permission denied"
2020-03-31T05:45:13.162Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Unable to open device /dev/input/event5 for inspectionUnable to find a suitable touch device"
2020-03-31T05:45:13.162Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "using Android InputManager"
2020-03-31T05:45:13.279Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] Reading minitouch banner
2020-03-31T05:45:13.322Z INF/device:plugins:touch 19143 [LMG820UMb681bd28] minitouch says: "Connection established"
2020-03-31T05:45:13.328Z INF/device:plugins:vnc 19143 [LMG820UMb681bd28] Starting VNC server on port 7490
2020-03-31T05:45:13.330Z INF/device:plugins:browser 19143 [LMG820UMb681bd28] Loading browser list
2020-03-31T05:45:13.347Z INF/device:plugins:browser 19143 [LMG820UMb681bd28] Updating browser list
2020-03-31T05:45:13.348Z WRN/device:plugins:browser 19143 [LMG820UMb681bd28] Unmapped browser "com.airfind.deltabrowser"
2020-03-31T05:45:13.349Z INF/device:plugins:mute 19143 [LMG820UMb681bd28] Will not mute master volume
2020-03-31T05:45:13.586Z INF/device:resources:minirev 19143 [LMG820UMb681bd28] Installing "/usr/lib/node_modules/stf/vendor/minirev/arm64-v8a/minirev" as "/data/local/tmp/minirev"
2020-03-31T05:45:13.796Z INF/device:plugins:forward 19143 [LMG820UMb681bd28] Launching reverse port forwarding service
2020-03-31T05:45:13.823Z INF/device:plugins:forward 19143 [LMG820UMb681bd28] Connecting to reverse port forwarding service
2020-03-31T05:45:14.000Z INF/device 19143 [LMG820UMb681bd28] Fully operational
```

I have the devices on hand if you want me to test anything

**Comment by koral--** [comment]
@man4567890 Is this issue different than that discussed in closed thread: https://github.com/openstf/minitouch/issues/49#issuecomment-604443356 ?
Anyway please answer the the last question in linked thread

**Comment by man4567890** [comment]
Hi @koral-- 

Android 10 support works for Samsung, Motorola etc, but not for LGE 32 and 64 bit, I opened this ticket as per the request from @nanoscopic in the https://github.com/openstf/minitouch/issues/49#issuecomment-604443356 thread

> I can verify though that Android 10 support is working though, and this ticket is correctly closed. You should open a new ticket with your other specific errors, and then see who can help you there.

Hope that helps?

**Comment by koral--** [comment]
OK thanks, now it is clear.
